# story_telling = ["Section 1: The Knight's Calling \
# In a world where vampires outnumbered every other creature, and darkness loomed over the land, a young knight named Sir Galen found himself standing at a crossroad.\
# The tales he had heard since childhood whispered through his mind, tales of heroes and legends who stood up against the vampire scourge. \
# These stories had shaped his beliefs, instilling in him the courage to face the impending darkness. With determination blazing in his eyes, \
# he took up his sword and embarked on a perilous adventure.",
#                "Armed with only his unwavering faith and the stories etched in his heart, Sir Galen sought the legendary sword known as ""Dawnbreaker."" It was said to be forged by the gods themselves, imbued with the power to vanquish any evil. His journey led him through treacherous forests, across desolate wastelands, and into long-abandoned crypts. At every turn, he encountered vampires, minions of the night craving the destruction of all life.",
#               "In a forgotten graveyard, Sir Galen faced his first test. A group of vampire fledglings, hungry for blood, emerged from the shadows, blocking his path. With swift strikes and precise parries, Sir Galen danced with the grace of a seasoned warrior. Despite their strength and speed, he stood firm, driving his blade into the hearts of the vampiric assailants. Their lifeless bodies fell to the ground, defeated by the knight's unwavering resolve.",
#                "As Sir Galen ventured deeper into the vampire-infested realms, he encountered a band of misfits who shared his cause. Among them was Selene, a vampire hunter seeking redemption for her cursed bloodline. Despite their differences, they formed an unlikely alliance, pooling their skills and knowledge in the fight against the vampire horde. Along their journey, they uncovered an ancient betrayal that had weakened the resistance against the vampires, adding fuel to their righteous fury.",
#                "Inside a crumbling cathedral, Sir Galen and Selene confronted a powerful vampire coven led by the ruthless Count Vladar. The air crackled with dark energy as the vampires unleashed their wrath. Sir Galen's sword clashed against their fangs and claws, while Selene's arrows found their marks with deadly precision. Together, they fought as one, their hearts aflame with a shared purpose. The battle raged on, and although outnumbered, the knight and the hunter held their ground, determined to slay the monstrous vampires.",
#                "Word of Sir Galen's quest and his alliance with Selene spread like wildfire across the vampire-dominated lands. The vampire overlords, sensing a threat to their dominion, unleashed their mightiest warriors to eradicate the knight and his companions. But Sir Galen had become a beacon of hope, inspiring ordinary people to rise against the vampiric tyranny. They joined him, a united force of resistance against the darkness that threatened to consume them all.",
#              "At the heart of the vampire realm, in a colossal fortress teeming with undead, Sir Galen and his allies faced the vampire lords themselves. It was a battle of epic proportions, the clash between the indomitable human spirit and the insidious strength of the vampires. Sir Galen's sword gleamed with divine light, striking down his foes, while Selene's crossbow bolts found their targets with unerring accuracy. The resistance fighters fought valiantly, their determination"]
